### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by hayate04** [mandiant/flare-vm#465] opened 2023-06-12 00:32 UTC
![image](https://github.com/mandiant/flare-vm/assets/136282034/4cf52443-0085-43e8-ba50-417c9052559c)

im just following the installation guide and i facing this error. anyone know how to fix it?

**Comment by Maciej-Koc** [comment] 2023-06-12 02:55
see #461

**Comment by mr-tz** [comment] 2023-06-12 07:13
duplicate of #461

**Closed by mr-tz** 2023-06-12 07:13 UTC
