### ISSUE TITLE
Flare-vm tools not installing

### ISSUE THREAD

**Issue by SUBHAMPAREEK** [mandiant/flare-vm#433] opened 2022-12-24 03:58 UTC
### Description

Every time i try to install the script it shows :
Error

"Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
At line:1 char:115
+ ... /main/install.ps1',"$([Environment]::GetFolderPath("Desktop"))\instal ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException"

![image](https://user-images.githubusercontent.com/24918171/209420963-7805b44f-d460-4b06-830a-c7c30c8ea1cf.png)

**Comment by MalwareMechanic** [comment] 2022-12-24 06:35
The exception appears to be thrown as a result of the `DownloadFile` call below:

https://github.com/mandiant/flare-vm/blob/fea9dbcd65375013dcb68924f945a2fafc1aedb2/install.ps1#L301-L304

This call is trying to download the file `https://raw.githubusercontent.com/mandiant/flare-vm/main/config.xml`. If you run the code below in an admin powershell prompt, does it also throw an exception?

```
(New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/mandiant/flare-vm/main/config.xml', "$(${Env:TEMP})\config.xml")
```

I'm curious, do you have an AV/EDR solution running that may be preventing the connection to the remote host?

**Comment by SUBHAMPAREEK** [comment] 2022-12-24 09:45
EDR/AV are not running. Still the same error


![image](https://user-images.githubusercontent.com/24918171/209430391-240fdd04-8655-47e7-96e5-d7f447556db1.png)

**Comment by MalwareMechanic** [comment] 2022-12-24 21:49
My next thought was that your VM might be in "host-only" mode, but I tried the same command I posted above with my VM in "host-only" mode and got the error: `"The remote name could not be resolved: 'raw.githubusercontent.com'"`, so I don't think your VM is in "host-only" mode.

Overall, this seems to be a networking issue rather than an issue with the script itself. Unfortunately I'm not sure if I'll be able to properly diagnosis the root cause. You could try connecting to a proxy or VPN and trying again. Also check if there's any firewall or IDS that may be preventing the remote connection to be established.

Let me know if you find the root cause!

**Comment by MalwareMechanic** [comment] 2022-12-26 13:53
Closing for now, we can re-open when more information is available

**Closed by MalwareMechanic** 2022-12-26 13:53 UTC

**Comment by Swapnil-Chatterjee** [comment] 2023-02-20 20:49
@SUBHAMPAREEK were you able to identify the error? If so, please share the workaround/solution.

**Comment by luk0y** [comment] 2023-05-05 15:59
@Swapnil-Chatterjee @SUBHAMPAREEK I used a VPN with a random US location and it worked successfully. Thank a lot @MalwareMechanic.
