### ISSUE TITLE
Post Install

### ISSUE THREAD

**Issue by 4zt3ch** [mandiant/flare-vm#572] opened 2024-03-04 02:49 UTC
### What's the problem?

After installation completes, 
A few things are missing from all the guides I’ve read.

1. FlareVM background does not change after installation and final restart.
(All the guides say this should tell you it was a success)

2. Folder for Failed Installed Packages, does not appear on desktop.
3.  A lot of desktop.ini fill in a lot of filesystem.
4. this is possibly something but I think it’s just the installer finished, saying installer.vm failed?
5.  Also a lot of the time it says during download, installer.vm (forced)??
Maybe this is all tied together somehow!

anyway I just want to make sure it is safe to run malware. I have the whole toolset now tho :)
Just want to make sure install was successful before running malware…

### Steps to Reproduce

Run installer.ps1

### Environment

ParrotOS
Virtualbox
Windows 10 eval 64 bit

**Comment by Ana06** [comment] 2024-03-04 16:40
I think this is a duplicate of https://github.com/mandiant/flare-vm/issues/573. There is a fix in https://github.com/mandiant/VM-Packages/pull/931 for that issue. @4zt3ch can you please try to install FLARE-VM again after that PR has been merged and re-open this issue if the problem is not fixed?

**Closed by Ana06** 2024-03-04 16:40 UTC
Labels: :bug: bug

**Comment by 4zt3ch** [comment] 2024-03-04 21:31
Ok, so how do I merge it? Will you bring merging it or will I be? Sent from my iPhoneOn Mar 4, 2024, at 9:40 AM, Ana María Martínez Gómez ***@***.***> wrote:﻿
I think this is a duplicate of #573. There is a fix in mandiant/VM-Packages#931 for that issue. @4zt3ch can you please try to install FLARE-VM again after that PR has been merged and re-open this issue if the problem is not fixed?

**Comment by 4zt3ch** [comment] 2024-03-05 05:19
Beautifully fixed !!!

**Comment by 4zt3ch** [comment] 2024-03-05 11:34
You fixed it! the install was a success!!

The only failed package was : x64dbg.ollydumpex.vm

Also had a question about the windows platform.
It asks after the install to turn on User Access Controls or something of that nature? I am assuming not to turn this on if it asks?
