### ISSUE TITLE
Add VSCode code/text editor

### ISSUE THREAD

**Issue by jstrosch** [mandiant/flare-vm#565] opened 2024-02-01 16:07 UTC
### Details

I'd like to propose adding VSCode to the FLARE-VM build. This has become a great open-source code editor with a lot of useful extensions and built-in capabilities. I also utilize the built-in syntax highlighting to help with code analysis, for example when viewing extracted macros. 

https://github.com/microsoft/vscode

According to https://code.visualstudio.com/docs/supporting/requirements, the install size is < 500mb. It's certainly provides a much smaller footprint than installing Visual Studio.

**Comment by emtuls** [comment] 2024-02-01 17:46
I am for this and have suggested it in https://github.com/mandiant/VM-Packages/issues/883 as well.

It looks like it's also readily available in Chocolately as well: https://community.chocolatey.org/packages/vscode

@jstrosch If you'd like to make a new metapackage request in `VM-Packages` to kick it off, that would be great!
https://github.com/mandiant/VM-Packages/issues/new/choose

**Comment by jstrosch** [comment] 2024-02-01 22:36
I created one at https://github.com/mandiant/VM-Packages/issues/887. I can't seem to find a shimmed executable for this package though and not sure what that impacts. I'm not very familiar with chocolatey structure though and could simply be overlooking it.

**Comment by Ana06** [comment] 2024-02-14 09:44
@jstrosch thanks for the tool proposal. Note that issues to propose new tools additions should be opened in VM-Packages (an not in FLARE-VM) as we need a package in VM-Pakckages that we can add to FLARE-VM. This also allows us to share packages with Commando-VM, so that in this case Commando VM users will also be able to install VSCode.

Closing this issue as it is duplicate of https://github.com/mandiant/VM-Packages/issues/887

**Closed by Ana06** 2024-02-14 09:44 UTC
