### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by d0razi** [mandiant/flare-vm#464] opened 2023-06-09 18:36 UTC
*** LOADING BOXSTARTER ***
ERROR: Cannot validate argument on parameter 'ArgumentList'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
The install of flarevm.installer.vm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\flarevm.installer.vm\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - flarevm.installer.vm (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\flarevm.installer.vm\tools\chocolateyinstall.ps1'.
 See log for details

The above error appears.

**Comment by mr-tz** [comment] 2023-06-10 11:16
duplicate of #461, likely a bug in Boxstarter

**Closed by mr-tz** 2023-06-10 11:16 UTC
