### ISSUE TITLE
Installation Error with chocolatey command

### ISSUE THREAD

**Issue by kaushik-reddy** [mandiant/flare-vm#459] opened 2023-06-07 08:43 UTC
Hello Guys, I am facing an issue with the installation. Please check the screenshot for the error details
![Screenshot 2023-06-07 141149](https://github.com/mandiant/flare-vm/assets/30206245/48d89036-d53a-4e66-97d6-5de231554f08)

**Comment by sadaseqw21** [comment] 2023-06-07 10:53
same

**Comment by Ana06** [comment] 2023-06-07 13:44
Closing this as it is a duplicate of https://github.com/mandiant/flare-vm/issues/458 

`$env:chocolateyVersion = '1.4.0'` only works if choco is not installed (as it is used to specify the version during installation). Otherwise you have to uninstall it. After uninstalling it, you can run `$env:chocolateyVersion = '1.4.0` and then the installation script as described in the README.

**Closed by Ana06** 2023-06-07 13:44 UTC
