### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by subhankarbhndr211** [mandiant/flare-vm#463] opened 2023-06-08 13:59 UTC
Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Refreshing environment variables from the registry for powershell.exe. Please wait...
Finished
Chocolatey v2.0.0
Installing the following packages:
flarevm.installer.vm
By installing, you accept licenses for the packages.
Progress: Downloading flarevm.installer.vm 0.0.0.20230606... 100%

flarevm.installer.vm v0.0.0.20230606 (forced)
flarevm.installer.vm package files install completed. Performing other installation steps.
 *** LOADING BOXSTARTER ***
ERROR: Cannot validate argument on parameter 'ArgumentList'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
The install of flarevm.installer.vm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\flarevm.installer.vm\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - flarevm.installer.vm (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\flarevm.installer.vm\tools\chocolateyinstall.ps1'.
 See log for details.
True

Errors       : {}
ComputerName : localhost
Completed    : True
FinishTime   : 08-06-2023 19:25:35
StartTime    : 08-06-2023 19:24:49

**Comment by ddarcy93** [comment] 2023-06-09 22:24
I have the exact same issue

**Comment by mr-tz** [comment] 2023-06-10 11:16
duplicate of #461, likely a bug in Boxstarter

**Closed by mr-tz** 2023-06-10 11:16 UTC
